<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Tagalys\Catalog\Block\Product\ProductList\Toolbar
 */
use Tagalys\Catalog\Block\Product\ProductList\Toolbar;

$params =$this->getRequest()->getParams();
$helper = $this->helper('Tagalys\CatalogSearch\Helper\Data');
$res=$helper->getTagalysSearchData();
?>

<?php if ($block->getCollection()->getSize()): ?>
    <div class="toolbar toolbar-products" data-mage-init='<?php /* @escapeNotVerified */ echo $block->getWidgetOptionsJson(); ?>'>
       <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
       <?php endif; ?>

	   <?php include ($block->getTemplateFile('Tagalys_Catalog::product/list/toolbar/amount.phtml')) ?>

	   <?php echo $block->getPagerHtml() ?>

	   <?php include ($block->getTemplateFile('Tagalys_Catalog::product/list/toolbar/limiter.phtml')) ?>

	  <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Tagalys_Catalog::product/list/toolbar/sorter.phtml')) ?>
       <?php endif; ?>

	</div>
<?php endif ?>